config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  root 'pages#home'
  get '/about' => 'pages#about'
  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :plan
  has_one :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  attr_accessor :stripe_card_token
  
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:message]
            ContactMailer.contact_email(name, email, body).deliver
            flash[:success] = 'Message sent.'
            redirect_to root_path
        else
            flash[:danger] = 'Error occured'
            redirect_to new_contact_path, notice: "Error Occurred. Message not sent."
        end
    end
    
    private
    def contact_params
        params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
    def about
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    before_action :only_current_user
    def new
        #form where user can fill out their own profile
        @user = User.find( params[:user_id] )
        @profile = @user.build_profile
    end
    def create
        @user = User.find ( params[:user_id] )
        @profile = @user.build_profile(profile_params)
        if @profile.save
            flash[:sucess] = "Profile Updated!"
            redirect_to user_path( params[:user_id] )
        else
            render action: :new
        end
    end
    
    def edit
        @user = User.find( params[:user_id] )
        @profile = @user.profile
    end
    
    def update
        @user = User.find( params[:user_id] )
        @profile = @user.profile
        if @profile.update_attributes(profile_params)
            flash[:success] = "Profile Updated!"
            redirect_to user_path( params[:user_id] )
        else
            render action: :edit
        end
    end
    
    private
    def profile_params
        params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :status, :description, :skills, :equipment)
    end
    
    def only_current_user
      @user = User.find( params[:user_id] )
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_filter :select_plan, only: :new
    def create
        super do |resource|
            if params[:plan]
                resource.plan_id = params[:plan]
                if resource.plan_id == 2
                    resource.save_with_payment
                else
                    resource.save
                end
            end
        end
    end
    private
    def select_plan
        unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
            flash[:notice] = "Please select a membership plan to sign up."
            redirect_to root_url
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def show
        @user = User.find( params[:id] )
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
      <h1 class="text-center">Contact H20</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
      <%= form_for @contact do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :message %>
          <%= f.text_area :message, class: 'form-control' %>
        </div>
        <%= f.submit 'Submit', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hollywood 2.0</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: "text/javascript" %>
  <%= javascript_include_tag 'application'%>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class='container'>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'H20', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="main-nav-collapse">
        <div class="nav navbar-nav navbar-right">
          <% if current_user %>
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
          <% else %>
            <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
          <% end %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact Us", new_contact_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>
     <%= yield %> 
  </div>


</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <h1>About Hollywood 2.0</h1>
    <p>Our primary goal is to create a network of entertainment professionals free from the constraints of location. Writers, Directors, Actors, Designers, and Crew Members can work together from across the globe.</p>
</div>

app/views/pages/home.html.erb
<%= link_to "Create your New Profile!", new_user_profile_path(current_user), class: 'btn btn-success btn-lg btn-block' if current_user  %>

<div class="mainBanner text-center">
    <h1>Hollywood 2.0</h1>
<p>A community of independent artists from around the world working together to provide quality entertainment.</p>
</div>
<div class="row">
     <%if user_signed_in? %>
        <div class="col-md-6">
            <div class="well">
                <h2 class="text-center">Your Profile</h2>
                <% if current_user.profile %>
                    <%= link_to "Edit Your Profile", edit_user_profile_path(user_id: current_user.id), class: "btn btn-default btn-lg btn-block" %>
                    <%= link_to "View Your Profile", user_path(current_user), class: "btn btn-default btn-lg btn-block" %>
                <%else%>
                    <p>Create your profile so you can connect with the community of filmmakers.</p>
                    <%= link_to "Create your profile!", new_user_profile_path(current_user), class: 'btn btn-primary btn-lg btn-block' if current_user %>
                <% end %>
            </div>
        </div>
        <div class="col-md-6">
            <div class="well">
                <h2 class="text-center">The Community</h2>
                <p>Visit the community and meet your fellow filmmakers, find jobs, and work on Independent projects!</p>
                <%= link_to "Visit the community", "#", class: 'btn btn-default btn-lg btn-block' %>
            </div>
        </div>
    <%else%>
        <div class="col-md-6">
            <div class="well">
                <h3 class="text-centered">Free Membership</h3>
                <ul>
                    <li>Create Profile</li>
                    <li>Upload Resume</li>
                    <li>Link to Reel and/or Portfolio</li>
                    <li>View User Profiles</li>
                    <li>View Projects</li>
                    <li>Post in Public Forums</li>
                </ul>
                </br>
                </br>
                <%= link_to "Sign Up Free", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
    
            </div>
        </div>
        <div class="col-md-6">
            <div class="well">
                <h3 class="text-centered">Pro Membership</h3>
                <ul>
                    <li>Create Profile</li>
                    <li>Upload Resume</li>
                    <li>Link to Reel and/or Portfolio</li>
                    <li>View User Profiles</li>
                    <li>Upload Photos and Videos</li>
                    <li>Contact other Users</li>
                    <li>Create and Post in Private Forums</li>
                    <li>Create Projects</li>
                </ul>
                <%= link_to "Sign Up for Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
            </div>
        </div>
    <%end%>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
    <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :job_title %>
        <%= f.select :job_title, ['Writer', 'Director', 'Producer', 'Director of Photography', 'Camera Operator', 'Assistant Camera', 'Production Assistant', 'Scenic Designer', 'Lighting Designer', 'Sound Designer', 'Audio Mixer', 'Audio Engineer', 'Boom Operator', 'Electrician', 'Grip', 'Costume Designer', 'Makeup'], {}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :contact_email %>
        <%= f.text_field :contact_email, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :status %>
        <%= f.select :status, ['Available', 'Occupied'], {}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :equipment %>
        <%= f.text_area :equipment, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :skills %>
        <%= f.text_area :skills, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center RegText">Edit Your Profile</h1>
        <p class="text-center RegText">Keep your profile up to date and stay in touch with the H2O community!</p>
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center RegText">Create Your Profile</h1>
        <p class="text-center RegText">Connect to the Hollywood 2.0 Network and Entertainment professionals in your area and around the world!</p>
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= @user %>
<%= image_tag @user.profile.avatar.url %>
<%= @user.profile.first_name %> <%= @user.profile.last_name %><br />
<%= @user.profile.job_title %><br />
<% if current_user.plan_id == 2 %>
    <%= @user.profile.phone_number %><br />
    <%= @user.profile.contact_email %><br />
    <% end %>
<%= @user.profile.status %><br />
<%= @user.profile.skills %><br />
<%= @user.profile.equipment %> <br />
    